name: Dotnet release (nuget)

on:
  release:
    types:
      - published
  push:
    branches:
      - master

jobs:
  unix-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-10.15, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Configure
      run: cmake -S . -Bbuild -DBUILD_TESTING=ON -DCMAKE_BUILD_TYPE=Release -DBUILD_DOTNET=ON -DBUILD_SHARED_LIBS=ON
    - name: Build
      run: cmake --build build --config Release --target all -v
    - name: Test
      run: cd build && ctest --verbose
    - name: Install
      run: cmake --build build --config Release --target install -v -- DESTDIR=install
    - name: Publish to NuGet
      run: |
        dotnet nuget push build/dotnet/packages/ -k ${NUGET_API_KEY} --skip-duplicate  -s https://api.nuget.org/v3/index.json
      continue-on-error: true

  windows-build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Install SWIG 4.0.2
      run: |
        (New-Object System.Net.WebClient).DownloadFile("http://prdownloads.sourceforge.net/swig/swigwin-4.0.2.zip","swigwin-4.0.2.zip");
        Expand-Archive .\swigwin-4.0.2.zip .;
        echo "$((Get-Item .).FullName)/swigwin-4.0.2" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
    - name: Check swig
      run: swig -version
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /verbosity:normal /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /verbosity:normal /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /verbosity:normal /maxcpucount
    - name: Publish to NuGet
      run: |
        dotnet nuget push build/dotnet/packages/ -k ${NUGET_API_KEY} --skip-duplicate  -s https://api.nuget.org/v3/index.json
      continue-on-error: true
