name: Windows Dotnet

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Check swig
      run: swig -version
    - name: Check cmake
      run: cmake --version
    - name: Configure
      run: cmake -S. -Bbuild -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON -DBUILD_DOTNET=ON
    - name: Build
      run: cmake --build build --config Release --target ALL_BUILD -- /verbosity:normal /maxcpucount
    - name: Test
      run: cmake --build build --config Release --target RUN_TESTS -- /verbosity:normal /maxcpucount
    - name: Install
      run: cmake --build build --config Release --target INSTALL -- /verbosity:normal /maxcpucount
